### ISSUE TITLE
Add example programs using the linkage-node library

### ISSUE THREAD

**Issue by KoenWestendorp** [Impossible-Robotics-5412/linkage#2]
In the future, when we implement the library in other languages as well, we can duplicate the examples and adapt them to work in the other language. 
This also serves as a soft way of testing the operation and ergonomics of the library. When we add a new feature to the library, I think we should also add a use of the feature to _the_ example or _one of many_ examples.

In fact, I think it would be better to have many smaller examples.
The code used for a robot that is actually in operation by Impossible Robotics might itself serve as a beautiful larger example, but that will simple reside in its own repo, I guess. We should link to that from the README when it becomes relevant.

**Comment by KoenWestendorp** [comment]
Of course, looking at you @BaukeWestendorp to do this actual work. But let me know if you want to discuss how we could put this into practice in a broad sense. We could also add examples for some other parts of the project, but that is something for another time.

**Comment by BaukeWestendorp** [comment]
We also have to think about unit tests for the linkage libraries. We could consider making the examples unit tests too? Kind of like rust documentation with examples being unit tests.

**Comment by BaukeWestendorp** [comment]
Added a simple example in with PR #31 but some more examples still should be added. There still are some issues when running Linkage Lib Node whenever you don't have Runtime already running. It will kill the program because the ALRM signal will kill it. This should be investigated and made into a separate issue.

**Comment by BaukeWestendorp** [comment]
A basic example exists for now. The linkage-node project will be completely revised in the near future, so more examples are unnecessary.
