### ISSUE TITLE
Generalize sending messages between programs into a single shared rust library

### ISSUE THREAD

**Issue by KoenWestendorp** [Impossible-Robotics-5412/linkage#20]
I converted this into an issue so we can discuss how we want to give this shape, and slowly work towards introducing it.

@BaukeWestendorp, I think we discussed that we wanted to create a shared MessageBytes thin wrapper for the 8-byte packages we send around. Then, we can create further wrappers and From and Into implementations to convert between the different semantically loaded types.

If there are any thoughts you have about how we can best go about this, please add them under this issue. I am especially interested in the needs we have as we work with this project.

**Comment by BaukeWestendorp** [comment]
First let's make an overview of what we currently do.

### Cockpit-Frontend **>** Cockpit-Backend
```
ENABLE_FRONTEND  = [0x00, 0, 0, 0, 0, 0, 0, 0]
DISABLE_FRONTEND = [0x01, 0, 0, 0, 0, 0, 0, 0]
```

### Cockpit-Frontend **<** Cockpit-Backend
```
FRONTEND_ENABLED  = [0x08, 0, 0, 0, 0, 0, 0, 0]
FRONTEND_DISABLED = [0x09, 0, 0, 0, 0, 0, 0, 0]
```

### Cockpit-Backend **>** Runtime
```
ENABLE        = [0x10, 0, 0, 0, 0, 0, 0, 0]
DISABLE       = [0x11, 0, 0, 0, 0, 0, 0, 0]
GAMEPAD_EVENT = [0x11, data...]
```

### Cockpit-Backend **<** Runtime
```
ENABLED  = [0x18, 0, 0, 0, 0, 0, 0, 0]
DISABLED = [0x19, 0, 0, 0, 0, 0, 0, 0]
```

### Linkage-Lib **>** Carburetor

_(note #1)_
```
MOTOR_INSTRUCTION = [0x40, data...] 
QUERY_BATTERY     = [0x80, 0, 0, 0, 0, 0, 0, 0]
QUERY_CPU         = [0x81, 0, 0, 0, 0, 0, 0, 0]
QUERY_MEMORY      = [0x82, 0, 0, 0, 0, 0, 0, 0]
```

### Linkage-Lib **<** Carburetor
```
BATTERY = [0x90, 0, 0, 0, 0, 0, 0, 0]
CPU     = [0x91, 0, 0, 0, 0, 0, 0, 0]
MEMORY  = [0x92, 0, 0, 0, 0, 0, 0, 0]
```

I think it might be useful to have an `InstructionMessage` and a `DataMessage`

`InstructionMessage` is responsible for all the simple one byte messages with just the instruction code.

`DataMessage` is responsible for sending the instruction code and some data that goes along with it _(just like we have at note #1)_.
When you make a new `DataMessage` you should be able to implement custom functions (`impl From for DataMessage` for example) to turn data like `(motor_channel, motor_speed)` into the 7 remaining data bytes.

This is what I've thought of so far but feel free to add things I've missed. I'm not sure how we would implement this in Rust, but I'm sure you do @KoenWestendorp .

**Comment by KoenWestendorp** [comment]
That is a wonderful write-up. Thanks!
