### ISSUE TITLE
When runtime is shut down while connected to cockpit-backend, cockpit-backend crashes.

### ISSUE THREAD

**Issue by BaukeWestendorp** [Impossible-Robotics-5412/linkage#24]
```
Encountered an error: failed to fill whole buffer
Enable a logger to see more information.
thread 'main' panicked at 'should connect to runtime: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }'
```

**Comment by BaukeWestendorp** [comment]
@KoenWestendorp could you take a look at how to do this? Currently mu rust knowledge is preventing me from fixing this so any help would be appreciated :)

**Comment by KoenWestendorp** [comment]
Investigating

**Comment by KoenWestendorp** [comment]
Alright. So I removed the `?` on `enable_linkage` and `disable_linkage` calls. These functions would return `Err` when runtime was shut down, because they could not read/write from it, since the connection was closed. The propagation of the error would make the `|msg| {}` handler closure
