### ISSUE TITLE
What will installation and usage look like?

### ISSUE THREAD

**Issue by KoenWestendorp** [Impossible-Robotics-5412/linkage#3]
I think it is a good idea to track some ideas on what the process of _installing_ and _using_ the project look like.

We need to create scripts and document the procedures of the following:

- [x] Installation
    - [x] Installing the software on the Raspberry Pi (_runtime_, _linkagelib_, _carburetor_)
    - [x] Installing the software on the host for _cockpit_ (_backend_, _frontend_)
- [ ] Usage
    - [x] How can everything be started up in only a small number of steps? We want this thing to be easy in operation, ultimately.
    - [ ] What does operation look like? Driving around and stuff, controlling, reading and understanding info from sensors.
    - [ ] What does proper shutdown look like?
    - [ ] What does emergency shutdown look like?
    - [x] What are safety precautions above what is warranted with any robot operation? 
          (In other words are there any things that have to do with our project that need to be taken into account to ensure safe operation? I actually think that most of this will be taken care of in the programs themselves--see graceful shutdowns on termination of _carburetor_, for example.)

**Comment by KoenWestendorp** [comment]
Additionally, we should perhaps add a subsection in **usage** describing the **configuration**.

This also leads us to a question of how to organize configuration. Do we use a single config file on the Pi, or separate ones despite their operation as a single entity.

**Comment by BaukeWestendorp** [comment]
> Additionally, we should perhaps add a subsection in **usage** describing the **configuration**.
> 
> 
> 
> This also leads us to a question of how to organize configuration. Do we use a single config file on the Pi, or separate ones despite their operation as a single entity.

I think a single configuration file is the most logical solution. When we eventually combine some of the rust code for communicating between programs into a shared rust library, we can add a config struct into that library that can be used over all rust programs on the pi so we don't have to write the code for reading the configuration file three times. (carburetor, linkage-lib and runtime)

**Comment by KoenWestendorp** [comment]
I agree, and I opened an issue (#4) about the implementation of such a config system.
We can do most of this work in parallel with for example the work on this issue. But in the end we will have to unify it. That means that this issue basically depends on #4. So if all unrelated steps have been done here, progress will be blocked by the config implementation. Until then, we can keep working on both.

**Comment by BaukeWestendorp** [comment]
Installation is documented in the README.
