### ISSUE TITLE
Carburetor slowly will consume more and more CPU the longer it's alive

### ISSUE THREAD

**Issue by BaukeWestendorp** [Impossible-Robotics-5412/linkage#68]
This probably has got to do with accumulating threads spawning, but I haven't investigated any of this.

**Comment by KoenWestendorp** [comment]
I might have the chance to look at this over the weekend. I think it has to do with threads accumulating as well.

**Comment by BaukeWestendorp** [comment]
This issue seems to have been resolved by intimidation with this issue.
