### ISSUE TITLE
Send backlog of logs before connecting with Cockpit

### ISSUE THREAD

**Issue by BaukeWestendorp** [Impossible-Robotics-5412/linkage#77]
We don't show the backlog of messages before the logger is connected. We should support sending a backlog of all messages sent before connecting with the logger.

**Comment by BaukeWestendorp** [comment]
@KoenWestendorp I assigned this to you, is that okay with you?

**Comment by KoenWestendorp** [comment]
I have been working on a little crate to do this. Tomorrow I might have a chance to look into making this work with the current tools and otherwise work on our own mechanism.

**Comment by BaukeWestendorp** [comment]
fixed in 64100f1
